import SidebarLayout from '@/components/sidebar/sidebar-layout';
import { ThemeProvider } from '@/context/theme-provider';
import { signOut } from '@/lib/auth';
import getSession from '@/lib/getSession';
import { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "../../globals.css";
import { SessionProvider } from 'next-auth/react';

const notoSans = Noto_Sans({ variable: '--font-sans' });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Lead Track",
    description: "Generated by create next app",
};

type Props = {
    children?: React.ReactNode;
}

export default async function RootLayout({ children }: Props) {
    const session = await getSession();

    console.log(session)

    if (!session) {
        redirect('/auth/signin?callbackUrl=/');
    }

    // allow only admin users
    // if (!["admin", "moderator"].includes(session.user.role)) {
    //     await signOut();
    // }

    // if (!session.user.profileCompleted) {
    //     redirect('/auth/new-user');
    // }

    return (
        <html lang="en" className={notoSans.variable}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <SessionProvider>
                        <SidebarLayout>
                            {children}
                        </SidebarLayout>
                    </SessionProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}