import { ThemeProvider } from '@/context/theme-provider';
import { Metadata } from 'next';
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const notoSans = Noto_Sans({ variable: '--font-sans' });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Lead Track",
    description: "Generated by create next app",
};

type Props = {
    children?: React.ReactNode;
}

export default function RootLayout({ children }: Props) {

    return (
        <html lang="en" className={notoSans.variable}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster richColors />
                </ThemeProvider>
            </body>
        </html>
    )
}